# Generated by Django 4.2.7 on 2023-11-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=200)),
                ('question_description', models.TextField()),
                ('likenum', models.IntegerField()),
                ('dislikenum', models.IntegerField()),
            ],
        ),
    ]
