# Generated by Django 4.2.7 on 2023-11-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HW1', '0001_initial_squashed_0004_user1_comment2_alter_likes_comment_alter_likes_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment2',
            new_name='comment',
        ),
        migrations.RenameModel(
            old_name='user1',
            new_name='user',
        ),
    ]
