# Generated by Django 4.2.7 on 2023-11-14 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HW1', '0006_profile_alter_comment_user_alter_likes_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='commentlist',
        ),
        migrations.RemoveField(
            model_name='question',
            name='taglist',
        ),
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HW1.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag1', to='HW1.tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag2', to='HW1.tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag3', to='HW1.tag'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HW1.profile'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HW1.comment'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HW1.profile'),
        ),
    ]
