# Generated by Django 4.2.7 on 2023-11-15 10:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('HW1', '0007_remove_question_commentlist_remove_question_taglist_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('a', django.db.models.manager.Manager()),
            ],
        ),
    ]
