# Generated by Django 4.2.7 on 2023-11-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HW1', '0008_alter_question_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
    ]
